"""ranking de fornecedores

Revision ID: 2d5868505fe8
Revises: ccf99514a856
Create Date: 2026-08-18 14:47:53.875220

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d5868505fe8"
down_revision: str | Sequence[str] | None = "ccf99514a856"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ranking_fornecedor",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("competencia", sa.String(length=6), nullable=False),
        sa.Column("cnpj", sa.String(length=20), nullable=False),
        sa.Column("itens_vencidos", sa.Integer(), nullable=False),
        sa.Column("licitacoes_distintas", sa.Integer(), nullable=False),
        sa.Column("valor_total", sa.Numeric(precision=38, scale=4), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ranking_fornecedor")),
    )
    op.create_index(
        op.f("ix_ranking_fornecedor_cnpj"), "ranking_fornecedor", ["cnpj"], unique=False
    )
    op.create_index(
        op.f("ix_ranking_fornecedor_competencia"),
        "ranking_fornecedor",
        ["competencia"],
        unique=False,
    )
    op.create_table(
        "ranking_fornecedor_total",
        sa.Column("cnpj", sa.String(length=20), nullable=False),
        sa.Column("itens_vencidos", sa.Integer(), nullable=False),
        sa.Column("licitacoes_distintas", sa.Integer(), nullable=False),
        sa.Column("valor_total", sa.Numeric(precision=38, scale=4), nullable=True),
        sa.PrimaryKeyConstraint("cnpj", name=op.f("pk_ranking_fornecedor_total")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ranking_fornecedor_total")
    op.drop_index(op.f("ix_ranking_fornecedor_competencia"), table_name="ranking_fornecedor")
    op.drop_index(op.f("ix_ranking_fornecedor_cnpj"), table_name="ranking_fornecedor")
    op.drop_table("ranking_fornecedor")
    # ### end Alembic commands ###
