"""indice do ranking de atipicidade

Revision ID: 5b5574552999
Revises: f3a91c72b104
Create Date: 2026-08-19 20:33:37.631354

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b5574552999"
down_revision: str | Sequence[str] | None = "f3a91c72b104"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_score_anomalia_posicao_ranking"),
        "score_anomalia",
        ["posicao_ranking"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_score_anomalia_posicao_ranking"), table_name="score_anomalia")
    # ### end Alembic commands ###
