"""competencia desnormalizada no score

Revision ID: 66f900b10f43
Revises: 5b5574552999
Create Date: 2026-08-22 16:56:03.066148

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66f900b10f43"
down_revision: str | Sequence[str] | None = "5b5574552999"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("score_anomalia", sa.Column("competencia", sa.String(length=6), nullable=True))
    op.create_index(
        "ix_score_anomalia_competencia_posicao",
        "score_anomalia",
        ["competencia", "posicao_ranking"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_score_anomalia_competencia_posicao", table_name="score_anomalia")
    op.drop_column("score_anomalia", "competencia")
    # ### end Alembic commands ###
