"""esquema inicial

Revision ID: cfaa5e5321f2
Revises:
Create Date: 2026-08-03 11:26:10.633871

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfaa5e5321f2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execucao_modelo",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("algoritmo", sa.String(length=50), nullable=False),
        sa.Column("parametros_json", sa.JSON(), nullable=False),
        sa.Column("metricas_json", sa.JSON(), nullable=False),
        sa.Column("janela_treino_inicio", sa.String(length=6), nullable=True),
        sa.Column("janela_treino_fim", sa.String(length=6), nullable=True),
        sa.Column("executado_em", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_execucao_modelo_tipo"), "execucao_modelo", ["tipo"], unique=False)
    op.create_table(
        "fornecedor",
        sa.Column("cnpj", sa.String(length=14), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("cnpj"),
    )
    op.create_table(
        "ingestao_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("competencia", sa.String(length=6), nullable=False),
        sa.Column("arquivo", sa.String(length=255), nullable=False),
        sa.Column("linhas_lidas", sa.Integer(), nullable=False),
        sa.Column("linhas_inseridas", sa.Integer(), nullable=False),
        sa.Column("linhas_atualizadas", sa.Integer(), nullable=False),
        sa.Column("linhas_rejeitadas", sa.Integer(), nullable=False),
        sa.Column("iniciado_em", sa.DateTime(), nullable=False),
        sa.Column("finalizado_em", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("mensagem_erro", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingestao_log_competencia"), "ingestao_log", ["competencia"], unique=False
    )
    op.create_table(
        "orgao",
        sa.Column("codigo_orgao", sa.String(length=10), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("codigo_orgao_superior", sa.String(length=10), nullable=True),
        sa.Column("nome_orgao_superior", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("codigo_orgao"),
    )
    op.create_table(
        "serie_mensal",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("competencia", sa.String(length=6), nullable=False),
        sa.Column("codigo_orgao", sa.String(length=10), nullable=True),
        sa.Column("codigo_modalidade", sa.Integer(), nullable=True),
        sa.Column("quantidade_licitacoes", sa.Integer(), nullable=False),
        sa.Column("valor_total", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("valor_mediano", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_serie_mensal_codigo_orgao"), "serie_mensal", ["codigo_orgao"], unique=False
    )
    op.create_index(
        op.f("ix_serie_mensal_competencia"), "serie_mensal", ["competencia"], unique=False
    )
    op.create_table(
        "previsao",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("execucao_id", sa.Integer(), nullable=False),
        sa.Column("serie_chave", sa.String(length=50), nullable=False),
        sa.Column("competencia_alvo", sa.String(length=6), nullable=False),
        sa.Column("alvo", sa.String(length=20), nullable=False),
        sa.Column("valor_previsto", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("ic_inferior", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("ic_superior", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.ForeignKeyConstraint(["execucao_id"], ["execucao_modelo.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_previsao_competencia_alvo"), "previsao", ["competencia_alvo"], unique=False
    )
    op.create_index(op.f("ix_previsao_execucao_id"), "previsao", ["execucao_id"], unique=False)
    op.create_index(op.f("ix_previsao_serie_chave"), "previsao", ["serie_chave"], unique=False)
    op.create_table(
        "unidade_gestora",
        sa.Column("codigo_ug", sa.String(length=10), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("codigo_orgao", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["codigo_orgao"],
            ["orgao.codigo_orgao"],
        ),
        sa.PrimaryKeyConstraint("codigo_ug"),
    )
    op.create_index(
        op.f("ix_unidade_gestora_codigo_orgao"), "unidade_gestora", ["codigo_orgao"], unique=False
    )
    op.create_table(
        "licitacao",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("numero_licitacao", sa.String(length=20), nullable=False),
        sa.Column("codigo_ug", sa.String(length=10), nullable=False),
        sa.Column("codigo_modalidade", sa.Integer(), nullable=False),
        sa.Column("modalidade", sa.String(length=100), nullable=False),
        sa.Column("numero_processo", sa.String(length=50), nullable=True),
        sa.Column("objeto", sa.Text(), nullable=True),
        sa.Column("situacao", sa.String(length=100), nullable=True),
        sa.Column("uf", sa.String(length=2), nullable=True),
        sa.Column("municipio", sa.String(length=100), nullable=True),
        sa.Column("data_abertura", sa.Date(), nullable=True),
        sa.Column("data_resultado", sa.Date(), nullable=True),
        sa.Column("valor", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("competencia", sa.String(length=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["codigo_ug"],
            ["unidade_gestora.codigo_ug"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "numero_licitacao", "codigo_ug", "codigo_modalidade", name="uq_licitacao_chave_natural"
        ),
    )
    op.create_index(
        op.f("ix_licitacao_codigo_modalidade"), "licitacao", ["codigo_modalidade"], unique=False
    )
    op.create_index(op.f("ix_licitacao_competencia"), "licitacao", ["competencia"], unique=False)
    op.create_index(
        op.f("ix_licitacao_data_abertura"), "licitacao", ["data_abertura"], unique=False
    )
    op.create_table(
        "item_licitacao",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("licitacao_id", sa.Integer(), nullable=False),
        sa.Column("codigo_item_compra", sa.String(length=30), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("quantidade", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("valor_item", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("cnpj_vencedor", sa.String(length=14), nullable=True),
        sa.ForeignKeyConstraint(
            ["cnpj_vencedor"],
            ["fornecedor.cnpj"],
        ),
        sa.ForeignKeyConstraint(["licitacao_id"], ["licitacao.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_item_licitacao_codigo_item_compra"),
        "item_licitacao",
        ["codigo_item_compra"],
        unique=False,
    )
    op.create_index(
        op.f("ix_item_licitacao_licitacao_id"), "item_licitacao", ["licitacao_id"], unique=False
    )
    op.create_table(
        "participante_licitacao",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("licitacao_id", sa.Integer(), nullable=False),
        sa.Column("codigo_item_compra", sa.String(length=30), nullable=False),
        sa.Column("cnpj_participante", sa.String(length=14), nullable=False),
        sa.Column("flag_vencedor", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cnpj_participante"],
            ["fornecedor.cnpj"],
        ),
        sa.ForeignKeyConstraint(["licitacao_id"], ["licitacao.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_participante_licitacao_cnpj_participante"),
        "participante_licitacao",
        ["cnpj_participante"],
        unique=False,
    )
    op.create_index(
        op.f("ix_participante_licitacao_licitacao_id"),
        "participante_licitacao",
        ["licitacao_id"],
        unique=False,
    )
    op.create_table(
        "score_anomalia",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("execucao_id", sa.Integer(), nullable=False),
        sa.Column("licitacao_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("posicao_ranking", sa.Integer(), nullable=True),
        sa.Column("features_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["execucao_id"], ["execucao_modelo.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["licitacao_id"], ["licitacao.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_score_anomalia_execucao_id"), "score_anomalia", ["execucao_id"], unique=False
    )
    op.create_index(
        op.f("ix_score_anomalia_licitacao_id"), "score_anomalia", ["licitacao_id"], unique=False
    )
    op.create_index(op.f("ix_score_anomalia_score"), "score_anomalia", ["score"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_score_anomalia_score"), table_name="score_anomalia")
    op.drop_index(op.f("ix_score_anomalia_licitacao_id"), table_name="score_anomalia")
    op.drop_index(op.f("ix_score_anomalia_execucao_id"), table_name="score_anomalia")
    op.drop_table("score_anomalia")
    op.drop_index(
        op.f("ix_participante_licitacao_licitacao_id"), table_name="participante_licitacao"
    )
    op.drop_index(
        op.f("ix_participante_licitacao_cnpj_participante"), table_name="participante_licitacao"
    )
    op.drop_table("participante_licitacao")
    op.drop_index(op.f("ix_item_licitacao_licitacao_id"), table_name="item_licitacao")
    op.drop_index(op.f("ix_item_licitacao_codigo_item_compra"), table_name="item_licitacao")
    op.drop_table("item_licitacao")
    op.drop_index(op.f("ix_licitacao_data_abertura"), table_name="licitacao")
    op.drop_index(op.f("ix_licitacao_competencia"), table_name="licitacao")
    op.drop_index(op.f("ix_licitacao_codigo_modalidade"), table_name="licitacao")
    op.drop_table("licitacao")
    op.drop_index(op.f("ix_unidade_gestora_codigo_orgao"), table_name="unidade_gestora")
    op.drop_table("unidade_gestora")
    op.drop_index(op.f("ix_previsao_serie_chave"), table_name="previsao")
    op.drop_index(op.f("ix_previsao_execucao_id"), table_name="previsao")
    op.drop_index(op.f("ix_previsao_competencia_alvo"), table_name="previsao")
    op.drop_table("previsao")
    op.drop_index(op.f("ix_serie_mensal_competencia"), table_name="serie_mensal")
    op.drop_index(op.f("ix_serie_mensal_codigo_orgao"), table_name="serie_mensal")
    op.drop_table("serie_mensal")
    op.drop_table("orgao")
    op.drop_index(op.f("ix_ingestao_log_competencia"), table_name="ingestao_log")
    op.drop_table("ingestao_log")
    op.drop_table("fornecedor")
    op.drop_index(op.f("ix_execucao_modelo_tipo"), table_name="execucao_modelo")
    op.drop_table("execucao_modelo")
    # ### end Alembic commands ###
