"""remove indice sem uso de codigo_item_compra

Revision ID: dbdfe5415a3a
Revises: 2d5868505fe8
Create Date: 2026-08-18 17:13:54.790483

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbdfe5415a3a"
down_revision: str | Sequence[str] | None = "2d5868505fe8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_item_licitacao_codigo_item_compra"), table_name="item_licitacao")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_item_licitacao_codigo_item_compra"),
        "item_licitacao",
        ["codigo_item_compra"],
        unique=False,
    )
    # ### end Alembic commands ###
